name: CI

on:
  push:

jobs:
  # Runs a TypeScript type check
  tsc:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules
        run: npm ci --no-fund
      - name: Run tsc
        run: npm run tsc
